#====================================#
#      spring boot configuration     #
#====================================#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kongxji?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#====================================#
#      framework configuration       #
#====================================#
spring:
  jpa:
    database-platform: org.kongxji.framework.jdbc.MySQL5DialectUTF8 #自动创建数据表自定义配置